### ISSUE TITLE
show error : core.require

### ISSUE THREAD

**Issue by Jayuda** [arboleya/electrify#76]
Hello, i was try electrify but show error : 
App threw an error when running [TypeError: core.require is not a function]
any clue ?
thanks

**Comment by Jayuda** [comment]
work well on upgrade to meteor 1.4
